from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.models import AnalysisReport


def build_pdf(report: AnalysisReport) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, title=f"TruthLens Report {report.id}")
    styles = getSampleStyleSheet()
    def footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica-Bold", 8)
        canvas.drawCentredString(306, 24, "Generated by TruthLens AI Engine | TEAM TRUTHLENS | See Truth. Stop Deception.")
        canvas.restoreState()

    disclaimer = (
        "This report has been generated using automated forensic analysis techniques. "
        "Results are probabilistic assessments and should be considered advisory in nature. "
        "TruthLens AI does not guarantee absolute authenticity or inauthenticity. "
        "Additional human verification is recommended for critical decisions."
    )

    story = [
        Paragraph("TruthLens AI", styles["Title"]),
        Paragraph("FORENSIC ANALYSIS REPORT", styles["Title"]),
        Paragraph("Synthetic Media & Cybersecurity Verification", styles["Heading2"]),
        Spacer(1, 12),
        Paragraph(f"Report ID: {report.id}", styles["Normal"]),
        Paragraph(f"Analysis Date: {report.uploaded_at}", styles["Normal"]),
        Paragraph("Version: 2.0.0", styles["Normal"]),
        Paragraph("Analyzed By: TruthLens AI Engine", styles["Normal"]),
        Spacer(1, 12),
        Paragraph("Submitted File Details", styles["Heading2"]),
        Paragraph(f"File: {report.filename}", styles["Normal"]),
        Paragraph(f"Detected media type: {report.media_type.title()}", styles["Normal"]),
        Paragraph(f"Decision: {report.verdict}", styles["Normal"]),
        Paragraph(f"Awareness: {report.awareness_message}", styles["Normal"]),
        Spacer(1, 12),
        Paragraph("Analysis Summary", styles["Heading2"]),
        Paragraph(report.analysis_summary, styles["BodyText"]),
        Spacer(1, 12),
    ]

    score_table = Table(
        [
            ["Authenticity", "AI Probability", "Risk Level", "Threat Score", "Confidence"],
            [
                f"{report.scores.authenticity_score}%",
                f"{report.scores.deepfake_probability}%",
                report.scores.risk_level,
                f"{report.scores.threat_score}%",
                f"{report.scores.confidence_score}%",
            ],
        ]
    )
    score_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111827")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.extend([score_table, Spacer(1, 14), Paragraph("Evidence", styles["Heading2"])])

    for item in report.evidence:
        story.append(Paragraph(f"<b>{item.label}</b> [{item.severity}]: {item.detail}", styles["BodyText"]))
        story.append(Spacer(1, 6))

    story.extend([Spacer(1, 8), Paragraph("Metadata Analysis", styles["Heading2"])])
    story.append(Paragraph(f"Codec: {report.metadata.codec}", styles["BodyText"]))
    story.append(Paragraph(f"File size: {report.metadata.file_size_mb} MB", styles["BodyText"]))
    story.append(Paragraph(f"Duration: {report.metadata.duration_seconds or 'N/A'} seconds", styles["BodyText"]))
    story.append(Paragraph(f"Camera: {report.metadata.camera_information}", styles["BodyText"]))
    story.append(Paragraph(f"Editing software: {report.metadata.editing_software}", styles["BodyText"]))
    story.extend([Spacer(1, 8), Paragraph("Visual Analysis / AI Artifact Detection", styles["Heading2"])])
    if report.image_forensics:
        for key, value in report.image_forensics.items():
            story.append(Paragraph(f"{key.replace('_', ' ').title()}: {value}", styles["BodyText"]))
    elif report.url_analysis:
        story.append(Paragraph(str(report.url_analysis), styles["BodyText"]))
    elif report.email_analysis:
        story.append(Paragraph(str(report.email_analysis), styles["BodyText"]))
    else:
        story.append(Paragraph("Visual/audio evidence summarized in module evidence.", styles["BodyText"]))
    story.extend([Spacer(1, 8), Paragraph("Key Findings", styles["Heading2"])])
    for finding in report.key_findings:
        story.append(Paragraph(f"- {finding}", styles["BodyText"]))
    story.extend([Spacer(1, 8), Paragraph("Reasons for Decision", styles["Heading2"])])
    for reason in report.reasons_for_decision:
        story.append(Paragraph(f"- {reason}", styles["BodyText"]))
    story.extend([Spacer(1, 8), Paragraph("Recommendations", styles["Heading2"])])
    for recommendation in report.recommendations:
        story.append(Paragraph(f"- {recommendation}", styles["BodyText"]))
    story.extend([Spacer(1, 8), Paragraph("Conclusion", styles["Heading2"])])
    story.append(Paragraph(report.conclusion, styles["BodyText"]))
    story.extend([Spacer(1, 8), Paragraph("Disclaimer", styles["Heading2"])])
    story.append(Paragraph(disclaimer, styles["Italic"]))
    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    return buffer.getvalue()
